Web_TimeTracker/Areas/Administrator/Controllers/OverviewController.cs
using Backend_TimeTracker.Management;
using GlobalDefinitions_TimeTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Backend_TimeTracker;
using Backend_TimeTracker.DataAccess;
using OMSManager.GlobalDefinitions;
using System.Web.Security;

namespace Web_TimeTracker.Areas.Administrator.Controllers
{
    public class OverviewController : Controller
    {
        // GET: Administrator/Overview
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        private void setCookies(UserProperty currentUser)
        {
            HttpCookie cookie = new HttpCookie("userDataTimeTracker");

            try
            {
                cookie["ID"] = Server.UrlEncode(currentUser.Id.ToString());
                cookie["UserName"] = Server.UrlEncode(currentUser.UserName);
                cookie["FirstName"] = Server.UrlEncode(currentUser.FirstName);
                cookie["LastName"] = Server.UrlEncode(currentUser.LastName);

                cookie.Expires = DateTime.Now.AddHours(8);
                Response.Cookies.Add(cookie);

                FormsAuthentication.SetAuthCookie(currentUser.UserName, false);
            }
            catch (Exception ex)
            {

            }
        }

        /** Methode zum löschen der Cookies **/
        private void removeCookies()
        {
            HttpCookie cookie = new HttpCookie("userDataTimeTracker");

            try
            {
                if (cookie != null)
                {
                    cookie.Values.Remove("ID");
                    cookie.Values.Remove("UserName");
                    cookie.Values.Remove("FirstName");
                    cookie.Values.Remove("LastName");

                    cookie.Expires = DateTime.Now.AddDays(-1);
                    Response.Cookies.Add(cookie);
                }

                FormsAuthentication.SignOut();
            }
            catch (Exception ex)
            {

            }
        }

        /** Methode überprüft ob Cookies noch vorhanden sind **/
        private bool proveCookies()
        {
            HttpCookie cookie = Request.Cookies["userDataTimeTracker"];

            if (cookie != null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

Web_TimeTracker/Areas/Employee/Controllers/TimeEntriesController.cs
using Backend_TimeTracker.Management;
using GlobalDefinitions_TimeTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Backend_TimeTracker;
using Backend_TimeTracker.DataAccess;
using OMSManager.GlobalDefinitions;
using System.Web.Security;

namespace Web_TimeTracker.Areas.Employee.Controllers
{
    public class TimeEntriesController : Controller
    {
        // GET: Employee/TimeEntries
        public ActionResult Index()
        {
            CustomerDB customerDB = new Backend_TimeTracker.DataAccess.CustomerDB();
            ProjectDB projectDB = new Backend_TimeTracker.DataAccess.ProjectDB();
            RepositoryDB repositoryDB = new Backend_TimeTracker.DataAccess.RepositoryDB();
            //Customer Dropdown
            var customerList = customerDB.GetCustomers();
            //Create List of SelectListItem
            List<SelectListItem> custselectlist = new List<SelectListItem>();
            foreach (CustomerProperty cust in customerList)
            {
                //Adding every record to list  
                custselectlist.Add(new SelectListItem { Text = cust.CustomerName, Value = cust.Id.ToString() });
            }

            ViewBag.SelectList = custselectlist;//Assign list to ViewBag will access this in view
       

            //Project Dropdown

            var projectList = projectDB.GetProjects();
            //Create List of SelectListItem
            List<SelectListItem> projselectlist = new List<SelectListItem>();
            foreach (ProjectProperty proj in projectList)
            {
                //Adding every record to list  
                projselectlist.Add(new SelectListItem { Text = proj.ProjectName, Value = proj.Id.ToString() });
            }

            ViewBag.projSelectList = projselectlist;//Assign list to ViewBag will access this in view
            

            //BusinessArea Dropdown

            var businessAreaList = repositoryDB.GetBusinessAreas();
            //Create List of SelectListItem
            List<SelectListItem> areaselectList = new List<SelectListItem>();
            foreach (BusinessAreaProperty area in businessAreaList)
            {
                //Adding every record to list  
                areaselectList.Add(new SelectListItem { Text = area.BusinessAreaName, Value = area.Id.ToString() });
            }

            ViewBag.areaSelectList = areaselectList;//Assign list to ViewBag will access this in view
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult AddEntry(TimeRecordingProperty currentTimeRecording)
        {

            string currentUserId;
            string currentUserFirstName;

            HttpCookie reqCookies = Request.Cookies["userDataFuhrparkManagement"];
            if (reqCookies != null)
            {
                currentUserId = reqCookies["ID"].ToString();
                currentUserFirstName = reqCookies["FirstName"].ToString();
            }
            currentUserId = currentTimeRecording.RecordingUserId.ToString();

            TimeRecordingDB timeRecordingDB = new TimeRecordingDB();

            TimeTrackerManager timeTrackerManager = new TimeTrackerManager();

            timeRecordingDB.InsertTimeRecording(currentTimeRecording);

            TimeTrackerManager.CreateTimeRecording(currentTimeRecording);

            TempData["InsertTimeRecordingFlag"] = "Eintrag erfolgreich erstellt";

            return RedirectToAction("Index", "Home");

            return View("Index");
        }
    }
}

Web_TimeTracker/Controllers/SecureController.cs
using GlobalDefinitions_TimeTracker.Models;
using OMSManager.Backend;
using OMSManager.GlobalDefinitions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Web_TimeTracker.Controllers
{
    public class SecureController : BaseController
    {
        private ADManager AdManager;
        private ADUser CurrentAdUser;

        public SecureController()
        {
            AdManager = new ADManager();
            CurrentAdUser = new ADUser();
        }

        public ActionResult Authentification()
        {
            string userRoles = string.Empty;

            string userName = HttpContext.Request.LogonUserIdentity.Name.Split('\\').LastOrDefault() ?? string.Empty;
            string domain = HttpContext.Request.LogonUserIdentity.Name.Split('\\').FirstOrDefault() ?? Domain;

            ViewBag.Error = string.Empty;

            try
            {
                if (ProveCookies())
                {
                    return RedirectToAction("", "");
                }

                CurrentAdUser = AdManager.GetADUser(Domain, Domain, userName);

                if(CurrentAdUser != null)
                {
                    if (!string.IsNullOrEmpty(CurrentAdUser.Department))
                    {
                        if (CurrentAdUser.Department.IndexOf("Projekte", StringComparison.OrdinalIgnoreCase) >= 0 ||
                            CurrentAdUser.Department.IndexOf("Lösungen", StringComparison.OrdinalIgnoreCase) >= 0)
                        {
                            if (!HandleUserDatabaseOperations())
                            {
                                Log4net.Logger.Error($"SecureController.Authentification.HandleUserDatabaseOperation Ein Fehler ist aufgetreten. Anwender {CurrentAdUser.AccountName} ");

                                return RedirectToAction("", "");
                            }
                            else
                            {
                                Log4net.Logger.Info($"SecureController.Authentification Anwender {CurrentAdUser.AccountName} hat sich erfolgreich angemeldet.");

                                SetCookies(userRoles);

                                return RedirectToAction("", "");
                            }
                        }
                        else
                        {
                            Log4net.Logger.Info($"SecureController.Authentification Anwender {CurrentAdUser.AccountName} hat sich versucht anzumelden ohne Berechtigung. Abteilung {CurrentAdUser.Department}");
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                Log4net.Logger.Error($"SecureController.Authentfication {ex.Message}");
            }

            return View();
        }

        private bool HandleUserDatabaseOperations()
        {
            UserProperty currentDBUser = new UserProperty();

            bool result = false;

            if(currentDBUser != null)
            {
                currentDBUser.UserName = CurrentAdUser.AccountName;
                currentDBUser.FirstName = CurrentAdUser.GivenName;
                currentDBUser.LastName = CurrentAdUser.Surname;
                currentDBUser.EMailAddress = CurrentAdUser.EMailAddress;
                currentDBUser.ManagerName = CurrentAdUser.Manager;
                currentDBUser.LastLogin = DateTime.Now;

                result = true;
            }
            else
            {
                currentDBUser = new UserProperty()
                {
                    UserName = CurrentAdUser.AccountName,
                    FirstName = CurrentAdUser.GivenName,
                    LastName = CurrentAdUser.Surname,
                    EMailAddress = CurrentAdUser.EMailAddress,
                    ManagerName = CurrentAdUser.Manager
                };

                result = true;
            }

            return result;
        }

        private void SetCookies(string userRoles)
        {
            HttpCookie cookie = new HttpCookie("timeTrackerUserData");

            try
            {
                SetCookieValues(cookie, userRoles);

                cookie.Expires = DateTime.Now.AddHours(8);
                Response.Cookies.Add(cookie);

                FormsAuthentication.SetAuthCookie(CurrentAdUser.AccountName, false);
            }
            catch (Exception ex)
            {
                Log4net.Logger.Error($"SecureController.SetCookies {ex.Message}");
            }
        }

        private void SetCookieValues(HttpCookie cookie, string userRoles)
        {
            cookie.Values["firstName"] = Server.UrlEncode(CurrentAdUser.GivenName);
            cookie.Values["lastName"] = Server.UrlEncode(CurrentAdUser.Surname);
            cookie.Values["userName"] = Server.UrlEncode(CurrentAdUser.AccountName);
            cookie.Values["roles"] = Server.UrlEncode(userRoles);
            cookie.Values["email"] = Server.UrlEncode(CurrentAdUser.EMailAddress);
            cookie.Values["phone"] = Server.UrlEncode(CurrentAdUser.Phone);
            cookie.Values["department"] = Server.UrlEncode(CurrentAdUser.Department);
            cookie.Values["manager"] = Server.UrlEncode(CurrentAdUser.Manager);
        }

        private void removeCookies()
        {
            HttpCookie cookie = new HttpCookie("timeTrackerUserData");

            try
            {
                if (cookie != null)
                {
                    cookie.Values.Remove("firstName");
                    cookie.Values.Remove("lastName");
                    cookie.Values.Remove("userName");
                    cookie.Values.Remove("userRoles");
                    cookie.Values.Remove("email");
                    cookie.Values.Remove("phone");
                    cookie.Values.Remove("department");
                    cookie.Values.Remove("manager");

                    cookie.Expires = DateTime.Now.AddDays(-1);
                    Response.Cookies.Add(cookie);
                }

                FormsAuthentication.SignOut();
            }
            catch (Exception ex)
            {
                Log4net.Logger.Error($"SecureController.RemoveCookies {ex.Message}");
            }
        }
    }
}

Web_TimeTracker/Views/Shared/_Layout.cshtml
@using Web_TimeTracker.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - TimeTracker</title>

    <!-- CSS -->
    <link rel="shortcut icon" type="image/x-icon" href="https://www.timetrackeriq.com/Images/TimeTracker/timetrackerlogo.svg">
    <link href="https://cdn.kendostatic.com/2022.2.621/styles/kendo.bootstrap-main.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Main.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Content.css")" rel="stylesheet" type="text/css" />

    <!-- Scripts -->
    <script src="https://cdn.kendostatic.com/2022.2.621/js/jquery.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.2.621/js/jszip.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.2.621/js/kendo.all.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.2.621/js/kendo.aspnetmvc.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.2.621/js/cultures/kendo.culture.de-DE.min.js"></script>

    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Script.js")"></script>

    <!-- Fontawesome Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Lobster Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">

    <!-- Sans Serif Font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800,300" rel="stylesheet" type="text/css">



</head>
<body>
    <main>
        <button class="openSideBar d-block d-md-none" onclick="openSideBar()" id="sideBarButton"><i class="fa fa-angle-double-right text-light"></i></button>

        <section class="sideBar d-none d-md-block" id="sideBar">
            <div class="d-flex flex-column flex-shrink-0 p-0 text-white" style="width: 280px; min-height: 100%; background: #000000 ">
                <div class="sideBar-title">
                    <h4 id="sideBarTitle"><i class="fa fa-clock-o"></i> TimeTracker</h4>
                </div>
                <div class="d-flex flex-column justify-content-between pre-scrollable" style="min-height: calc(100vh - 150px)">
                    <ul class="navbar-nav nav-pills flex-column mb-auto">
                        <li class="title pb-1">
                            Mein Profil
                        </li>
                        <li class="pt-1">
                            <a href="@Url.Action("Dashboard", "Overview", new { area = "Administrator" }, null)" class="nav-link text-light h6 @Html.IsActive("Overview", "Dashboard")">
                                <i class="fa fa-home text-light"></i>
                                <p class="d-inline">Startseite</p>
                            </a>
                        </li>
                        <li class="pt-1">
                            <a href="@Url.Action("Index", "TimeEntries", new { area = "Employee" }, null)" class="nav-link text-light h6 @Html.IsActive("TimeEntries", "Index")">
                                <i class="fa fa-home text-light"></i>
                                <p class="d-inline">Neue Zeit erstellen</p>
                            </a>
                        </li>
                        <li class="pt-1">
                            <a href="@Url.Action("", "", new { area = "" }, null)" class="nav-link text-light h6 @Html.IsActive("", "")">
                                <i class="fa fa-home text-light"></i>
                                <p class="d-inline">Zeiterfassungen</p>
                            </a>
                        </li>

                        <li class="title pb-1">
                            Administration
                        </li>
                        <li class="pt-1">
                            <a href="@Url.Action("", "", new { area = "" }, null)" class="nav-link text-light h6 @Html.IsActive("", "")">
                                <i class="fa fa-clock-o text-light"></i>
                                <p class="d-inline">Alle Zeiten</p>
                            </a>
                            <a href="@Url.Action("", "", new { area = "" }, null)" class="nav-link text-light h6 @Html.IsActive("", "")">
                                <i class="fa fa-file text-light"></i>
                                <p class="d-inline">Auswertungen</p>
                            </a>
                            <a href="@Url.Action("", "", new { area = "" }, null)" class="nav-link text-light h6 @Html.IsActive("", "")">
                                <i class="fa fa-archive text-light"></i>
                                <p class="d-inline">Alle Anträge</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>

        <section class="content">
            <div class="header-top d-flex bg-white">
                <div class="container-fluid">
                    <div class="header-top-left float-left">
                    </div>
                    <div class="header-top-right float-right">
                        <div class="login-panel float-right">
                            <img src="~/Content/Web/Images/User.png" height="20" style="border-radius:20em" />

                            <button class="btn btn-sm dropdown-toggle p-0 pl-2" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ernad Jakupovic
                            </button>
                            <div class="dropdown-menu">
                                <a class="btn" href="@Url.Action("Logout", "Secure", new { area = "" }, null)" role="button"><i class="fa fa-sign-out"></i> Abmelden</a>
                            </div>
                        </div>
                        <div class="top-language float-right">
                            <img src="https://images.vexels.com/media/users/3/164056/isolated/preview/56f4034aadb54a8f811fe73fd9352813-deutschland-flaggensprache-icon-kreis-by-vexels.png" height="20" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid mt-4">
                @RenderBody()
            </div>

            <footer class="fixed-bottom" id="footer">
                <div class="container text-center" id="footer-text">
                    &copy; PP 2000 GmbH | TimeTracker <small>v0.0.1</small> | Ernad Jakupovic
                </div>
            </footer>
        </section>
    </main>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelectorAll('.sidebar .nav-link').forEach(function (element) {

                element.addEventListener('click', function (e) {

                    let nextEl = element.nextElementSibling;
                    let parentEl = element.parentElement;

                    if (nextEl) {
                        e.preventDefault();
                        let mycollapse = new bootstrap.Collapse(nextEl);

                        if (nextEl.classList.contains('show')) {
                            mycollapse.hide();
                        } else {
                            mycollapse.show();
                            // find other submenus with class=show
                            var opened_submenu = parentEl.parentElement.querySelector('.submenu.show');
                            // if it exists, then close all of them
                            if (opened_submenu) {
                                new bootstrap.Collapse(opened_submenu);
                            }
                        }
                    }
                }); // addEventListener
            }) // forEach
        });
    </script>
</body>
</html>